camel:
  springboot:
    # The Camel context name
    name: Hoge API
  component:
    servlet:
      mapping:
        contextPath: /*

server:
  address: 0.0.0.0
  max-http-header-size: 64000
  # https://community.pivotal.io/s/article/spring-boot-app-rejects-http-request-with-total-header-size-larger-than-8kb

spring:
  # Spring JDBC configuration
  datasource:
    # Let Spring Boot auto-configure an embedded HSQL database
    url:

# Binding health checks to a different port
management:
  port: 8081

# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true
